spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/clientdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  application:
    name: clientservice

server:
  port: 8080

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:client.exchange}
  routing-key: ${RABBITMQ_ROUTING_KEY:client.created}
  queue: ${RABBITMQ_QUEUE:client.created.queue}

jwt:
  secret: ${JWT_SECRET:verysecretkeythatshouldbelongandcomplex123456}

logging:
  level:
    root: INFO
    com.ralphdoe.clientservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/clientservice.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
